all:
	g++ -I src/include -L src/lib -o main main.cpp SortingAlgs.cpp main_menu.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf
# all:
#     g++ -I src/include -L src/lib -o main main.cpp SortingAlgs.cpp main_menu.cpp -static-libgcc -static-libstdc++ -Wl,-Bstatic -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -Wl,-Bdynamic
